[workspace]
members = [
    "crates/tuack-ng",
    "crates/tuack-lib",
    "crates/tuack-config",
    "crates/tuack-utils",
    "crates/tuack-ng-parser",
    "crates/tuack-plugin-sdk",
]
resolver = "3"

[workspace.package]
version = "1.1.0-alpha.3"
edition = "2024"
authors = ["Pulsar <Pulsar33550336@163.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/tuackng/tuack-ng"

[workspace.dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
codespan-reporting = "0.13.1"
termcolor = "1"
bytesize = { version = "2.3.1", features = ["serde"] }
indexmap = { version = "2.13.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["rc"] }
serde_bytes = "0.11.19"
serde_many = { version = "0.1.0", features = ["derive"] }
tokio = "1.49.0"
tuack-ng-parser = { version = "1.0.3", path = "crates/tuack-ng-parser" }
thiserror = "2.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.debug-release]
inherits = "release"
lto = false
codegen-units = 16
strip = false
debug = 2
