[package]
name = "tuack-ng-parser"
version = "1.0.3"
edition = "2024"
description = "Markdown parser for Tuack-NG, based on rushdown"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tuackng/tuack-ng"
homepage = "https://github.com/tuackng/tuack-ng"
keywords = ["markdown", "parser", "ast", "tuack-ng", "typst"]
categories = ["parser-implementations", "text-processing"]
rust-version = "1.85"

[dependencies]
rushdown = "0.18"
serde = { workspace = true, features = ["derive"], optional = true }
unicode-width = "0.1"

[features]
serde = ["dep:serde"]

[dev-dependencies]
serde_json = "1"
